### ISSUE TITLE
Make Amici not return memory-intensive quantities

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/parPE#242]
Currently, Amici computes many quantities, such as the Jacobian, which are memory intensive for large-scale systems. When simulating a system with many conditions, as the rdata objects are stored in the RAM, this may cause crashes due to hundreds of Jacobians with millions of entries being stored temporarily...

**Comment by dweindl** [comment]
Probably after https://github.com/ICB-DCM/AMICI/issues/587
For short-term solution, the uninteresting ReturnData members could be emptied.

**Comment by paulstapor** [comment]
Indeed related. In the best case, Amici can be given a corresponding flag for the quantities to be computed, and parPE should pass only the necessary flags to Amici.

**Comment by dweindl** [comment]
https://github.com/ICB-DCM/AMICI/pull/1044 is included in #282 

Need to revisit which data we really need.

**Comment by paulstapor** [comment]
> [ICB-DCM/AMICI#1044](https://github.com/ICB-DCM/AMICI/pull/1044) is included in #282
> 
> Need to revisit which data we really need.

Agreed. Will have a look into that, but right now is just not the bet moment...

**Comment by dweindl** [comment]
Has been lying around for a while but needs to be addressed now:

Ensure correct setting of `amici::Solver::rdata_mode`. For optimization we generally want `amici::RDataReporting::likelihood`, but for hierarchical optimization we need `amici::RDataReporting::residuals` (otherwise no model outputs). For simulations we want  `amici::RDataReporting::full` or `amici::RDataReporting::residuals`, depending on whether states are to be saved.

**Comment by paulstapor** [comment]
Ok, would take care of this this week...
